on:
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write

name: Release Please

env:
  NODE_ENV: production

jobs:
  check-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun install
      - run: bun run build
      - run: bun run test

  release-please:
    runs-on: ubuntu-latest
    needs: check-build
    outputs:
      created: ${{ steps.release.outputs.releases_created }}
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node

  publish:
    name: Publish to npm
    needs: release-please
    if: ${{ needs.release-please.outputs.created == 'true' }}
    uses: ./.github/workflows/release.yaml
    secrets: inherit

  docs:
    name: Build Docs
    needs: release-please
    if: ${{ needs.release-please.outputs.created == 'true' }}
    uses: ./.github/workflows/docs.yaml
